name: build-booster-bot

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.2.0'
      label:
        description: 'Label'
        required: false
        default: ''
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [ Release ]

    runs-on: windows-latest

    env:
      Solution_Path: src/BoosterBot.sln
      Project_Path: src/BoosterBot/BoosterBot.csproj
      Version_Number: ${{ github.event.inputs.version || '1.2.0' }}    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Restore
      run: dotnet restore ${{ env.Solution_Path }}
      
    - name: Set label
      id: set_label
      run: |
        $label = '${{ github.event.inputs.label }}'
        if ('${{ github.event_name }}' -eq 'push') {
          $build = '.${{ github.run_number }}'
          if ($label) {
            if (-not $label.StartsWith("-")) {
                $label = "-" + $label
            }
            echo "label=$build$label" >> $env:GITHUB_OUTPUT
          }
          else {
            echo "label=$build-preview" >> $env:GITHUB_OUTPUT
          }
        }
        else {
          echo "label=$label" >> $env:GITHUB_OUTPUT
        }
      shell: pwsh
    
    - name: Update version
      run: |
        $label = '${{ github.event.inputs.label }}'
        if ($label) {
            if (-not $label.StartsWith("-")) {
                $label = "-" + $label
            }
        }
        
        $csprojPath = "${{ env.Project_Path }}"
        $csprojContent = Get-Content $csprojPath -Raw
        $newVersion = "${{ env.Version_Number }}$label"
        Write-Output "Version number: $newVersion"
        $updatedContent = $csprojContent -replace '(<Version>).*(</Version>)', "`${1}$newVersion`$2"
        Set-Content -Path $csprojPath -Value $updatedContent
      shell: pwsh
        
    - name: Build
      run: dotnet build ${{ env.Solution_Path }} --configuration Release

    - name: Publish
      run: dotnet publish ${{ env.Project_Path }} -o './artifacts/booster-bot-v${{ env.Version_Number }}${{ steps.set_label.outputs.label }}' --configuration Release -r win-x64 --self-contained true
      
    - name: Purge artifacts
      uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.API_REPOSITORY_PAT }}
        expire-in: 0
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 'booster-bot-v${{ env.Version_Number }}${{ steps.set_label.outputs.label }}'
        path: ./artifacts
